---
apiVersion: v1
kind: Service
metadata:
  name: 'github-app2-service'
  labels:
    app: 'github-app2'
spec:
  type: NodePort
  selector:
    app: 'github-app2'
  ports:
    - name: 'github-app2-port1'
      protocol: TCP
      port: 8086
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'github-app2'
  namespace: 'github-source'
  labels:
    app: 'github-app2'
spec:
  selector:
    matchLabels:
      app: 'github-app2'
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: 'github-app2'
    spec:
      containers:
        - name: 'github-app2'
          image: '${baseImgUrl}'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: '100m'
              memory: 
                100Mi
            limits:
              cpu: '200m'
              memory: '200Mi'
