---
apiVersion: v1
kind: Service
metadata:
  name: github-0307-service
  labels:
    app: github-0307
spec:
  type: NodePort
  selector:
    app: github-0307
  ports:
    - name: github-0307-port1
      protocol: TCP
      port: 8083
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-0307
  namespace: github-source
  labels:
    app: github-0307
spec:
  selector:
    matchLabels:
      app: github-0307
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: github-0307
    spec:
      containers:
        - name: sourcecontainer
          image: '${baseImgUrl}'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: '100m'
              memory: '100Mi'
            limits:
              cpu: '300m'
              memory: '300Mi'
